import{a as b,S as q,i}from"./assets/vendor-BXArD3N5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&d(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function h(s,r){const e={key:"55130808-0237c91bd8603b9007a67866c",q:s,image_type:"photo",orientation:"horizontal",per_page:15,page:r,safesearch:!0};return(await b.get("https://pixabay.com/api/",{params:e})).data}const M=new q(".gallery a"),f=document.querySelector(".gallery"),y=document.querySelector(".loader"),l=document.querySelector(".js-more");console.log(l);function g(s){const r=s.map(e=>`<li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <div>likes${e.likes}</div>
        <div>views${e.views}</div>
        <div>comments${e.comments}</div>
        <div>downloads${e.downloads}</div>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function P(){f.innerHTML=""}function p(){y.classList.remove("is-hidden")}function v(){y.classList.add("is-hidden")}function L(){l.classList.remove("is-hidden")}function w(){l.classList.add("is-hidden")}const m=document.querySelector(".js-form");let c,n=1,a=1;const S=15;m.addEventListener("submit",async s=>{if(s.preventDefault(),c=new FormData(s.target).get("search-text").trim(),c==="")return i.error({title:"помилка валідації",message:"заповніть поля"});n=1,a=0,p(),w(),P();try{const e=await h(c,n);if(a=Math.ceil(e.totalHits/S),e.hits.length===0){i.error({title:"помилка запиту",message:"нічого не знайдено за вашим запитом"});return}if(g(e.hits),a<=1){i.info({message:"We're sorry, but you've reached the end of search results."});return}L()}catch{a=0,i.error({title:"помилка запиту",message:"щось трапилось під час запиту"});return}finally{v()}m.reset()});l.addEventListener("click",async s=>{n+=1,p(),w();try{const r=await h(c,n);if(g(r.hits),$(),n>=a){i.info({message:"We're sorry, but you've reached the end of search results."});return}L()}catch{n-=1,i.error({title:"помилка запиту",message:"щось трапилось під час запиту"});return}finally{v()}});function $(){const r=f.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
