import{a as b,S as q,i as a}from"./assets/vendor-BXArD3N5.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function h(s,r){const e={key:"55130808-0237c91bd8603b9007a67866c",q:s,image_type:"photo",orientation:"horizontal",per_page:15,page:r,safesearch:!0};return(await b.get("https://pixabay.com/api/",{params:e})).data}const M=new q(".gallery a"),f=document.querySelector(".gallery"),g=document.querySelector(".loader"),c=document.querySelector(".js-more");console.log(c);function y(s){const r=s.map(e=>`<li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <div>likes${e.likes}</div>
        <div>views${e.views}</div>
        <div>comments${e.comments}</div>
        <div>downloads${e.downloads}</div>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",r),M.refresh()}function P(){f.innerHTML=""}function p(){g.classList.remove("is-hidden")}function L(){g.classList.add("is-hidden")}function v(){c.classList.remove("is-hidden")}function w(){c.classList.add("is-hidden")}const m=document.querySelector(".js-form");let n,i=1,u=1;const S=15;m.addEventListener("submit",async s=>{if(s.preventDefault(),n=new FormData(s.target).get("search-text").trim(),i=1,n==="")return a.error({title:"помилка валідації",message:"заповніть поля"});p(),w(),P();try{const e=await h(n,i);console.log(e),u=Math.ceil(e.totalHits/S),e.hits.length===0&&a.error({title:"помилка запиту",message:"нічого не знайдено за вашим запитом"}),y(e.hits)}catch{a.error({title:"помилка запиту",message:"щось трапилось під час запиту"})}L(),u>1&&v(),m.reset()});c.addEventListener("click",async s=>{i+=1,p(),w();try{const r=await h(n,i);y(r.hits),$()}catch{a.error({title:"помилка запиту",message:"щось трапилось під час запиту"})}L(),i<u&&v()});function $(){const r=f.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
